### ISSUE TITLE
issues on beta.stochss.org

### ISSUE THREAD

**Issue by briandrawert** [StochSS/stochss#770] opened 2019-12-17 17:13 UTC
1. need "click here to get started" button on front page
2. "report issue" link should open in new tab
3. Logout should be "quit" -> should kill the pod (stop the user container)
4. When 4 users were logged in, container would not start, simulations would not complete

**Comment by briandrawert** [comment] 2019-12-17 17:19
- Status "running" does not update on ensemble jobs
- On model editor page,  should not have number of trajectories (only shows 1)

**Comment by briandrawert** [comment] 2019-12-17 18:14
When I waited for the server to startup, it finally gave this error:

```
 Server requested
2019-12-17 18:12:14+00:00 [Warning] 0/1 nodes are available: 1 Insufficient memory.
Spawn failed: Timeout
```

**Comment by BryanRumsey** [comment] 2019-12-17 20:46
"report issue" link should open in new tab has been addressed in the convert-to-sbml branch

**Comment by BryanRumsey** [comment] 2019-12-17 20:48
number of trajectories has been addressed on the stocks-beta-issues branch

**Comment by BryanRumsey** [comment] 2019-12-18 03:48
Click Here To Get Started button has been added to the home page.
Could not reproduced the job status update error.

**Comment by briandrawert** [comment] 2019-12-19 16:19
"Logout" should only appear when logged in

**Closed** 2020-04-06 16:57 UTC
