### ISSUE TITLE
Stochoptim job status

### ISSUE THREAD

**Issue by bbbales2** [StochSS/stochss#473] opened 2015-06-22 17:37 UTC
If a stochoptim job is launched in the ec2 cloud, and the cloud is stopped while the job is still running, the job stays in the running status instead of switching to failed.

**Comment by briandrawert** [comment] 2015-06-25 23:28
This may not be fixable.

**Comment by briandrawert** [comment] 2015-06-26 22:28
The problem is that we can not use celery to query if a job exists in the flex-cloud queue.  Status is always "PENDING".  Moving this to 1.7

**Closed** 2020-07-08 23:11 UTC
Labels: bug
