### ISSUE TITLE
Still apt-get installs numpy 1.6.0 if you use pip

### ISSUE THREAD

**Issue by JohnAbel** [StochSS/stochss#289] opened 2015-02-08 02:37 UTC
This is still the same issue, I thought we had fixed it? I don't use a system-wide numpy install through apt-get, instead I use pip. StochSS installs with apt-get so it overwrites any numpy I have.

**Comment by bbbales2** [comment] 2015-02-08 19:50
Hopefully if you use run.generic.sh StochSS doesn't try to install any
system libraries. Is this not the case?

Ben

**Comment by JohnAbel** [comment] 2015-02-08 21:16
I used run.ubuntu.sh, should I be using generic?

**Comment by bbbales2** [comment] 2015-02-08 22:02
run.generic.sh shouldn't install any dependencies. If you use that it's up
to you to get the system dependencies. Exact system dependencies aren't
documented so well but basically you'll get errors in the run script until
you get it right

**Comment by bbbales2** [comment] 2015-03-09 21:13
Duplicate of https://github.com/StochSS/stochss/issues/171

**Closed by bbbales2** 2015-03-09 21:13 UTC
Labels: duplicate
